import:
  - ../common

normalization: softmax
num_classes: 2
data_len: 300

###################
# Training Config
###################
num_workers: 8
batch_size: 16
epochs: 200
lr: 1.0e-2
weight_decay: 0.0

###################
# Model Config
###################
model: deit_small_patch16_224_ctx_product_50_shared_qkv

clip_pretrained: false
checkpoint: false
checkpoint_nchunks: 2
